### ISSUE TITLE
Error in README and in description at marketplace.visualstudio.com 

### ISSUE THREAD

**Issue by aknew** [jkzing/vscode-redux-devtools#10]
Hello.
You have error in your README.md file and in description at marketplace.visualstudio.com, last point of Quick start has this listing:
```
let composeEnhancers = composeWithDevTools({
    realtime: true,
    name: 'Your Instance Name',
    host: '127.0.0.1',
    port: 1024, // the port your remotedev server is running at
});
```
but RemoteReduxDevToolsOptions which is pushed into composeWithDevTools hasn't field **host**, it has field **hostname**.

**Comment by jkzing** [comment]
Thanks! 😄
