### ISSUE TITLE
Question about capability

### ISSUE THREAD

**Issue by capozzic1** [jkzing/vscode-redux-devtools#12]
Hello, 

Would this tool work with an Angular app that has ngrx(basically redux for Angular)? I'm not allowed to install Chrome extensions so I wonder if this would be a good alternative for debugging redux for an Angular app.

**Comment by jkzing** [comment]
@capozzic1 , yes, I think it would work. What you need to do is to start a `remotedev-server` and integrate `remote-redux-devtools` in your code. See [https://github.com/jkzing/vscode-redux-devtools#quick-start] for more details.
