### ISSUE TITLE
vscode.previewHtml will be deprecated and removed soon.

### ISSUE THREAD

**Issue by blopez2010** [jkzing/vscode-redux-devtools#13]
Since last vscode update, I got next warning in vscode, please fix it! I really like this extension 😄 

`
Extension 'jingkaizhao.vscode-redux-devtools' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.
`

**Comment by jkzing** [comment]
Fixed in v1.0.0, please upgrade your extension.

See [CHANGELOG](https://github.com/jkzing/vscode-redux-devtools/blob/master/CHANGELOG.md) for more details.
