### ISSUE TITLE
Ability for React only

### ISSUE THREAD

**Issue by minkir014** [jkzing/vscode-redux-devtools#18]
Can I inspect an app that has react only and don't have redux?

**Comment by minkir014** [comment]
@jkzing Are you here??? Can you answer my question?

**Comment by jkzing** [comment]
@minkir014 Sorry for delay of response, quite busy these days…

For you question, short answer is, no you can not. 

This is redux devtool, not react devtool. For react development you can use react devtool chrome extension.
