### ISSUE TITLE
state is undefined

### ISSUE THREAD

**Issue by radziksh** [jkzing/vscode-redux-devtools#3]
I installed the application, configured the port, but can not see anything in the state. Restart does not help.

environment:
vsCode 1.12.1
typescript: 2.3.2
node: 7.4.0
webpack: 2.5.1

Screenshots:
![screenshot_142](https://cloud.githubusercontent.com/assets/1275228/26043871/598f7b9e-3949-11e7-8e6c-735256a9fd8a.png)
![screenshot_143](https://cloud.githubusercontent.com/assets/1275228/26043872/5b91ba9c-3949-11e7-8ba0-cc686b62f033.png)
![screenshot_144](https://cloud.githubusercontent.com/assets/1275228/26043945/d4fad90e-3949-11e7-8dde-ce44b3f8f7c1.png)

**Comment by jkzing** [comment]
Um...it seems you didn't have a `remotedev` server running on you localhost, and you did not compose your `remote-redux-devtools` middleware as well.

Please try following steps to setup:
1. `npm install remotedev remote-redux-devtools --save-dev`
2. create a file named *remotedev.js* (or any name you want)
3. in **remotedev.js**:
  ```javascript
  const remotedev = require('remotedev-server');

  remotedev({
      hostname: '127.0.0.1',
      port: 8080,
  });
  ```
4. run **remotedev.js** in shell
```bash
node remotedev.js
```
5. in your configureStore.js:
  ```javascript
  import {createStore, applyMiddleware} from 'redux';
  import {composeWithDevTools} from 'remote-redux-devtools';

  let compose = composeWithDevTools({
      realtime: true,
      name: 'Your Instance Name',
      host: '127.0.0.1',
      port: 1024, // the port your remotedev server is running at
  });

  const store = createStore(
      yourReducer,
      compose(
          applyMiddleware(...),
          persistState(...)
      )
  );
  ```
6. open your react-redux app in browser
7. open `vscode-redux-devtools` in vscode
