### ISSUE TITLE
Wrong characters shown in Mac

### ISSUE THREAD

**Issue by juangl** [jkzing/vscode-redux-devtools#4]
I'm using Mac OS X and I'm getting those characters wrong.
![screen shot 2017-07-10 at 22 05 50](https://user-images.githubusercontent.com/1887029/28049310-186e31b0-65bc-11e7-9a10-6e182fa691bf.png)

**Comment by jkzing** [comment]
Thanks for trying vscode-redux-devtools.😄

This is a [known issue](https://github.com/jkzing/vscode-redux-devtools#known-issues), because of `remotedev-app` bundle doesn't contain the font icon reference. I'll see what I can do.

**Comment by juangl** [comment]
Awesome! Thanks for doing this!

**Comment by jkzing** [comment]
@juangl Woo...I finally worked this out!!! 😆😆😆🚀🚀🚀

![image](https://user-images.githubusercontent.com/2851517/31450330-c3ab1124-ae6e-11e7-893d-fc921cbce845.png)
